name: Build Aseprite macOS ARM64

on:
  workflow_dispatch:

permissions:
  contents: write   # 允许创建 Release 与上传资产

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies via Homebrew
        run: |
          brew update
          brew install cmake ninja python

      - name: Download Skia binary for ARM64
        run: |
          # 使用官方预编译的 Skia-m102 macOS Release arm64 包
          curl -L -o skia.zip \
            https://github.com/aseprite/skia/releases/download/m102/Skia-macOS-Release-arm64.zip
          unzip skia.zip -d skia
        # Skia-macOS-Release-arm64.zip 来自 Skia-m102 release :contentReference[oaicite:0]{index=0}

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_OS_BACKEND=skia \
            -DSKIA_DIR=${{ github.workspace }}/skia \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -G Ninja

      - name: Build Aseprite
        run: ninja -C build aseprite

      - name: Package .app bundle
        run: |
          cd build
          mv Release/*.app Aseprite.app
          zip -r aseprite-mac-arm64.zip Aseprite.app

      - name: Create GitHub Release (draft)
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}-mac-arm64
          release_name: "Aseprite macOS ARM64 Build ${{ github.run_number }}"
          draft: true

      - name: Upload asset to Release
        uses: actions/upload-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/aseprite-mac-arm64.zip
          asset_name: aseprite-mac-arm64.zip
          asset_content_type: application/zip
