name: Build Aseprite macOS ARM64

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest  # macOS 环境，Apple Silicon 已默认支持

    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install build dependencies via Homebrew
        run: |
          brew update
          brew install cmake ninja python pkg-config \
            jpeg-turbo libpng webp freetype harfbuzz \
            bzip2 zlib libtiff

      - name: Download Skia binary for ARM64
        run: |
          SKIA_VER="m124-08a5439a6b"
          SKIA_URL="https://github.com/aseprite/skia/releases/download/${SKIA_VER}/Skia-macOS-Release-arm64.zip"
          curl -L -o skia.zip "$SKIA_URL"
          unzip skia.zip -d skia

      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=${{ github.workspace }}/skia \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DLIBJPEG_TURBO_INCLUDE_DIR=/opt/homebrew/include \
            -DLIBJPEG_TURBO_LIBRARY=/opt/homebrew/lib/libjpeg.a \
            -G Ninja


      - name: Build Aseprite
        run: ninja -C build aseprite Aseprite.app

      - name: Debug check contents
        run: ls -l build/bin

      - name: Package release bundle
        run: |
          cd build
          mkdir AsepriteBundle
          cp -r bin/Aseprite.app AsepriteBundle/
          cp -r data AsepriteBundle/
          cp bin/aseprite AsepriteBundle/
          cp ../aseprite.ini AsepriteBundle/ || true
          xattr -cr AsepriteBundle
          zip -r aseprite-mac-arm64.zip AsepriteBundle

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/aseprite-mac-arm64.zip
          draft: true
          tag_name: v${{ github.run_number }}-mac-arm64
          name: "Aseprite macOS ARM64 Build ${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
